Project/urls.py
import imp
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("app.urls")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from . import views

app_name="app"

urlpatterns = [
    path('',views.index,name="index"),
    path('home/',views.home,name="home"),
    path('hai/<name>',views.hainame,name="hai"),
    path('add/<a>/<b>',views.add,name="add"),
    path('temp/',views.tempdemo,name="tempdemo"),
    path('grt/<a>/<b>',views.grt2,name="grt2"),
    path('homepage/',views.hometemp,name="hometemp"),
    path('aboutus/',views.abouttemp,name="aboutus"),
    path('register/',views.register,name="register"),
    # path("profile/<id>",views.show_data,name="profile"),
]

app/models.py
from distutils.command.upload import upload
from pyexpat import model
from random import choices
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Skills(models.Model):
    skillname=models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.skillname
class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    gender=models.CharField(max_length=10,choices=(("Male","Male"),("Female","Female"),("Other","Other")))
    work_type=models.CharField(max_length=30,choices=(("part_time","part_time"),("Full_time","Full_time")))
    skills=models.ManyToManyField(Skills,related_name="profiles")
    profile_pic=models.ImageField(upload_to="profile_pic")

    def __str__(self) -> str:
        return self.user.first_name

app/forms.py
from django import forms
from django.contrib.auth.models import User
from app.models import *


class UserForm(forms.ModelForm):
    password=forms.CharField(max_length=100,min_length=8,widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ("username","email","first_name","last_name")

class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=('gender','work_type','skills','profile_pic')

app/views.py
from django.shortcuts import render
from django.http import HttpResponse



# Create your views here.
def index(request):
    return HttpResponse('<h1>Welcome to the project</h1>')

def home(request):
    return HttpResponse('<h1>welcome to homepage</h1>')

def hainame(request,name):
    return HttpResponse('<h2>Hello {}</h2>'.format(name))

def add(request,a,b):
    return HttpResponse("<h1>The sum of {} & {} is {}</h1>".format(a,b,int(a)+int(b)))
    

def tempdemo(request):
    fruits=['apple','banana','chikku','mango','dragon friut']
    return render(request,"template1.html",
    context={'name':"akshay",'Profession':"Data Scientist",'fruits':fruits})

def grt2(request,a,b):
    return render(request,"template2.html",context={'a':int(a),'b':int(b)})


def hometemp(request):
    return render(request,"Pages/home.html")

def abouttemp(request):
    return render(request,"Pages/about.html")

from django.core.files.storage import FileSystemStorage
from app.models import *
from django.contrib.auth.models import User
from app.forms import UserForm,ProfileForm

def register(request):
    if request.method=="POST":
        user=UserForm(request.POST)
        profile=ProfileForm(request.POST,request.FILES)
        if user.is_valid() and profile.is_valid():
            password=user.cleaned_data["password"]
            user=user.save(commit=False)
            user.set_password(password)
            user.save()
            profile=profile.save(commit=False)
            profile.user=user
            profile.save()
            
        # first_name=request.POST.get("first_name")
        # last_name=request.POST.get("last_name")
        # username=request.POST.get("username")
        # email=request.POST.get("email")
        # password=request.POST.get("pwd")
        # gender=request.POST.get("gender")
        # worktype=request.POST.get("worktype")
        # skills=request.POST.getlist("skills")
        # if request.FILES:
        #     file=request.FILES['profilepic']
        # user=User(username=username,email=email,first_name=first_name,last_name=last_name)
        # user.set_password(password)
        # user.save()
        # user_profile=Profile.objects.get_or_create(user=user,gender=gender,work_type=worktype,profile_pic=file)[0]

        # #user=Profile.objects.get_or_create(name=name,email=email,gender=gender,profile_pic=file)[0]
        # for i in skills:
        #     sk=Skills.objects.get(skillname=i)
        #     user_profile.skills.add(sk)
        # user_profile.save()
        
        return HttpResponse("<h1>Form Submitted Successfully</h1>")
    userform=UserForm()
    profileform=ProfileForm()
    return render(request,"Pages/register.html",context={"userform":userform,"profileform":profileform})


# def show_data(request,id):
#     data=Register.objects.all()
#     return render(request,"Pages/profile.html",{"datas":data})

templates/Pages/about.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  <title>AboutUs Page</title>
{% endblock %}

{% block content %}
  <div class="container">
    <h1>AboutUs Page</h1>
  </div>
{% endblock %}

templates/Pages/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  <title>Home Page</title>
{% endblock %}

{% block content %}
  <div class="container">
    <h1>Home Page</h1>
  </div>
{% endblock %}

templates/Pages/profile.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  <title>Profile</title>
{% endblock %}

{% block content %}
  <table border="2ptpt">
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Gender</th>
        <th>JobType</th>
        <th>Skills</th>
        <th>Profile_Pic</th>
    </tr>
    {% for data in datas %}
    <tr>
        <td>{{data.name}}</td>
        <td>{{data.email}}</td>
        <td>{{data.gender}}</td>
        <td>{{data.work_type}}</td>
        <td>
            {% for skill in data.skills.all %}
                {{skill}} 
            {% endfor %}
        </td>
        <td><img src="{{data.profile_pic.url}}" alt="No Image" width="50" height="50"></td>
    </tr>
    {% endfor %}
    
  </table>
{% endblock %}

templates/Pages/register.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  <title>Register</title>
{% endblock %}

{% block content %}
<div class="container">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- First_name : <input type="text" name="first_name" id="first_name"><br><br>
    Last_name : <input type="text" name="last_name" id="last_name"><br><br>
    Username : <input type="text" name="username" id="username">
    Email : <input type="email" name="email" id="email"><br><br>
    Password : <input type="password" name="pwd" id="pwd">
    Gender<select name="gender" id="gender">
        <option value="Male">Male</option>
        <option value="Female">Female</option>
        <option value="Other">Other</option>
    </select><br><br>
    <h4>Work Type</h4>
    Part-time : <input type="radio" name="worktype" id="worktype" value="Part-Time"><br>
    Full-time : <input type="radio" name="worktype" id="worktype" value="Full-Time"><br>
    <h4>Skills</h4>
    Java : <input type="checkbox" name="skills" id="Java" value="Java"> <br>
    Python : <input type="checkbox" name="skills" id="Pyhton" value="Python"> <br>
    PHP :  <input type="checkbox" name="skills" id="PHP" value="PHP"> <br>
    <br>
    <input type="file" name="profilepic" id="profilepic"> -->
    
    {{userform.as_p}}
    {{profileform.as_p}}
    <input type="submit" value="Register">
  </div>
  </form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Base HTML</title>
    {% endblock %}
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
    <!-- including the navbar partial -->
    {% include "partials/_navbar.html" %}
      {% block content %}
        <h1>Base Page</h1>
      {% endblock %}
</body>
</html>

templates/partials/_navbar.html
{% load static %}
<ul class="nav justify-content-center">
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="{% url 'app:hometemp' %}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'app:aboutus' %}">AboutUs</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'app:register' %}">Register</a>
    </li> 
    <!-- <li class="nav-item">
      <a class="nav-link disabled">Disabled</a>
    </li> -->
  </ul> -->

templates/template1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Template 1</title>
</head>
<body>
    <ul>
        <li>Lorem ipsum dolor sit amet, consectetuer adipiscing 
        elit. Aenean commodo ligula eget dolor. Aenean 
        massa.</li>
        <li>Cum sociis natoque penatibus et magnis dis 
        parturient montes, nascetur ridiculus mus. Donec quam 
        felis, ultricies nec, pellentesque eu, pretium quis, 
        sem.</li>
        <li>Nulla consequat massa quis enim. Donec pede justo, 
        fringilla vel, aliquet nec, vulputate eget, arcu.</li>
        <li>In enim justo, rhoncus ut, imperdiet a, venenatis 
        vitae, justo. Nullam dictum felis eu pede mollis 
        pretium. Integer tincidunt.</li>
      </ul>
      PARAGRAPH

      <h1>hello {{name}}</h1>
      <h2>welcome to {{Profession}} Position</h2>
      <ol>
        {% for fruit in fruits %}
        <li>{{fruit}}</li>
      {% endfor %}
      <h1><a href="{% url 'app:grt2' a=10 b=4 %}">Template</a></h1>
      </ol>
      
</body>
</html>

templates/template2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Greatest of 2 numbers</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% if a > b %}
      <h1>{{a}}</h1>
    {% else %}
      <h1>{{b}}</h1>
    {% endif %}
<h1><a href="{% url 'app:tempdemo' %}">Template</a></h1>
<img src="{% static 'images/photo.jpg' %}" width="100pt" height="100pt" alt="">
</body>
</html>